Zapper-fi/protocol

- docusaurus.config.ts
> docs(studio): Default to dark mode

- vercel.json
Redirecting https://protocol.zapper.xyz/docs/interpretation/app-token-interpretation/guide/getting-started
to https://protocol.zapper.xyz/docs/Interpretation/position-interpretation/guide/getting-started
> Redirect ATI page

- package.json
- pnpm-lock.yaml
> Bump to v3.6.0

- src/css/custom.scss
> Remove the table stripe background

- docusaurus.config.ts
- package.json
- pnpm-lock.yaml
Remove mermaid plugin and theme since there are no UML diagarams
> Remove mermaid

- package.json
- pnpm-lock.yaml
Remove the explicit theme-classic dependency as this is redundant when preset-classic is present
> Remove theme-classic

- src/css/custom.scss
- src/modules/Api/ApiSection.tsx
- src/pages/index.module.scss
- tailwind.config.js
- Reduce custom CSS classes
- Reduce duplicate declarations, use css variables
> CSS cleanup

- src/modules/Dashboard/BuyCredits.tsx
- src/modules/Dashboard/Note.tsx
- src/modules/Dashboard/PaymentHistory.tsx
This adjusts the credit costs to 1$ for 1k credits, per the new docs. Also moves the grace period to 5k credits.
> smol(studio): Adjust credit amounts to 1k credits / USD

- docs/api-intro/portfolio/app-balances.md
- docs/api-intro/portfolio/claimables.md
- docs/api-intro/portfolio/nft-balances.md
- docs/api-intro/portfolio/portfolio-totals.md
- docs/api-intro/portfolio/token-balances.md
Some sandbox links had been broken due to new page structure. 
This fixes it.
> smol(studio): Update sandbox links

- docs/api-intro/human-readable-transactions/account-timelines.md
- src/components/ApolloSandboxComponent.tsx
> set isSigner & realtimeInterpretation to true

- docs/api-intro/api-intro.md
- docs/api-intro/code-samples.md
- docs/api-intro/pricing.md
- docs/api-intro/sandbox.md
This adds a `Code Samples` section in the API docs. 
Gives code samples to query our api in React, Node, CURL, Python and Ruby.
> feat(studio): Add better code samples in multiple languages

- docs/api-intro/code-samples.md
These are improvements to the `Code Samples` section.
Added links to relevant languages docs, clarified API key encoding, cleaned up some code examples.
> smol(studio): Improve some code sample docs

- docs/api-intro/code-samples.md
This adds better docs for API key encoding, and setup guides for each language providedm in the `Code samples` API docs section.
> feat(studio): Add setup guides & encoding

- src/modules/Dashboard/BuyCredits.tsx
This : 
- Makes sure we round off the provided credit amount before fetching for the price of those credits
- Adds a prettier error message for when the credit amount provided is under our lower limit (5k)
> smol(studio): Improve buy credits error message

- docs/api-intro/api-intro.md
- src/modules/Dashboard/BuyCredits.tsx
- src/modules/Dashboard/ConsumptionStats.tsx
- src/pages/dashboard.tsx
This removes the note we had at the top of the dashboard saying we're in alpha. 
All our costs, credits and everything are ready for release, so not relevant anymore.
Also cleaned up font size.
> smol(studio): Remove alpha note

- src/modules/Metrics.tsx
This updates the stats we have on the protocol landing page.
> smol(studio): Hyperscale stats

- docs/api-intro/api-intro.md
- src/modules/Metrics.tsx
- src/pages/index.tsx
Moves the stats section higher on the landing page. 
Improves padding and font size in api docs.
> smol(studio): Move up stats, form

- src/modules/Metrics.tsx
Adds linking to the chains page form the chain amount on the landing page.
> feat(studio): Link chain amount to chains page

- docs/api-intro/onchain-identity.md
Moves the `account` query to `accounts`.
> smol(studio): Update accounts query docs

- docs/api-intro/pricing.md
- src/modules/Intro/Intro.tsx
- src/modules/Problem/Problem.tsx
> updated landing copy

- docs/api-intro/migration-checklist.md
> add-migration-checklist

- docs/api/api.md
Adds a link to start building with an AI agent.
> Add agent note

- docs/api/migration-checklist.md
Few slim downs to the migration docs!
> smol(studio): Slim migration docs a bit

- docs/api/agents.md
- docs/api/endpoints/_category_.json
- docs/api/endpoints/human-readable-transactions/_category_.json
- docs/api/endpoints/nft-queries/_category_.json
- docs/api/endpoints/onchain-identity.md
- docs/api/endpoints/onchain-prices.md
- docs/api/endpoints/portfolio/_category_.json
- docs/api/legacy-rest-api/_category_.json
- docs/api/legacy-rest-api/legacy-api-docs.md
- docs/api/legacy-rest-api/migration-checklist.md
- docs/api/pricing.md
- docs/api/sandbox.md
- docs/api/supported-chains.md
Adds the legacy docs to the REST API section. 
Also redoes the page numbers properly.
> feat(studio): Add legacy docs in legacy section, redo page numbers

- src/modules/Dashboard/SignInButton.tsx
Change navbar Customer Support link
> email support

- src/modules/Metrics.tsx
> smol(studio): Update chain amount

- src/modules/Dashboard/SignInButton.tsx
Reverts Zapper-fi/protocol#145
> Revert "email support"

- docs/api/agents.md
- docs/api/api.mdx
- docs/api/endpoints/human-readable-transactions/account-timelines.md
- docs/api/endpoints/human-readable-transactions/app-timelines.md
- docs/api/endpoints/nft-queries/nft-collection-holdings.md
- docs/api/endpoints/nft-queries/nft-collections.md
- docs/api/endpoints/nft-queries/nft-net-worth.md
- docs/api/endpoints/nft-queries/nft-token-holdings.md
- docs/api/endpoints/nft-queries/nft-token.md
- docs/api/endpoints/onchain-identity.md
- docs/api/endpoints/onchain-prices.md
- docs/api/endpoints/portfolio.md
- src/components/SignInDashboardButton.tsx
Went over the whole docs and added some improvements and removed superfluous descriptions, types, etc.
> feat(studio): Multiple docs improvements

- docusaurus.config.ts
> updating core copy to hone in on messaging

- docs/api/pricing.md
small improvements to copy on the pricing page. goal to make it more concise and easy to understand.
> improve pricing page

- src/modules/Dashboard/BuyCredits.tsx
This : 
- Removes the error message we had for too small credit amounts, and replaces it with a min input size of the min 5k points
- Adds a clearer message for seeing credit discounts
- Adds a credit +/- picker
> smol(studio): Credit picker +/-, adjusted credit cost message

- src/modules/Dashboard/BuyCredits.tsx
Fetches the cost of credits for the minimum 5k amount on load.
Also adjusts picker.
> smol(studio): Fetch credit costs on load

- src/modules/Intro/Intro.tsx
- src/pages/index.module.scss
> tiny edits

- src/modules/Dashboard/BuyCredits.tsx
This uses the new cost breakdown endpoint to provide a detailed overfew of the credit cost calculations.
> Studio use new endpoint

- src/modules/Dashboard/BuyCredits.tsx
Moves around the cost per credit for a cleaner breakdown.
Also adds some visual improvements.
> smol(studio): Improve breakdown

- src/modules/Dashboard/BuyCredits.tsx
> smol(studio): Update column label

- src/modules/Dashboard/BuyCredits.tsx
> smol(studio): Smol padding

- src/css/custom.scss
- src/modules/Dashboard/BuyCredits.tsx
- src/pages/dashboard.tsx
> fix(checkout): fix checkout UI

- src/components/Features.tsx
> fix(docs): Prevent flash when clicking on cards

- src/modules/Dashboard/BuyCredits.tsx
- src/modules/Dashboard/Profile.tsx
This ensures that new clients get their free 5k points displayed as free plan (regression, this was removed for some reason)
Also fixes display of api key and copy message (also a regression)
> feat(studio): Free tier on null credits, adjust api key display

- biome.json
- src/components/ApolloSandboxComponent.tsx
- src/components/Features.tsx
- src/components/QuickLinks.tsx
- src/components/SupportedChains.tsx
- src/modules/Api/ApiSection.tsx
- src/modules/Dashboard/BuyCredits.tsx
- src/modules/Dashboard/Chart/ChartTabs.tsx
- src/modules/Dashboard/ConsumptionStats.tsx
- src/modules/Dashboard/Note.tsx
- src/modules/Problem/Problem.tsx
- src/modules/Token/Token.tsx
- src/pages/dashboard.tsx
- src/pages/documentation/index.tsx
- src/theme/Root.js
Run biome and autofix
Moving forward, will be handled by https://github.com/Zapper-fi/protocol/pull/175
> chore(general): Run biome

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
Run linter before committing files
> chore(docs): Add linter as part of workflow

- docs/partials/_tab-human-readable.mdx
- docs/partials/_tab-portfolio-tracking.mdx
> smol(docs): Sub tabs height

- src/components/SupportedChains.tsx
Merge icon and text column in supported chains table
> chore(docs): Merge icon and text column

- vercel.json
Redirect /docs/litepaper (404) to Docs homepage
> chore(docs): Redirect litepaper url

- src/components/Card.tsx
- src/css/custom.scss
Align table styles with Zapper web
> fix(docs): Table styles

- src/modules/Dashboard/SignInButton.tsx
Adds icon to go to dashboard and logout, only visible in compact mode : 
Interim fix until we figure out long term solution.
> fix(studio): Show dashboard options on mobile

- src/components/Card.tsx
- src/modules/Dashboard/ConsumptionStats.tsx
> fix(dashboard): Fixed chart height

- src/helpers/formatDate.ts
- src/modules/Dashboard/PaymentHistory.tsx
> chore(docs): Tweak payment history table

- src/modules/Dashboard/BuyCredits.tsx
> fix(dashboard): Alignment

- src/pages/dashboard.tsx
Adjusts the dashboard layout. 
Fixes the fact that previously, when we zoomed, we entered full page mode and could never go back to split view.
> smol(studio): Modify dashboard layout

- src/pages/dashboard.tsx
Removes hardcoded widths, allows for resizing windows
> smol(studio): Improve dashboard when shrink

- src/modules/Dashboard/BuyCredits.tsx
Mobile popup was being blocked for mobile checkout flow. 
This opens a new tab for mobile, while staying with a popup on web.
> feat(studio): Open new tab on mobile checkout

- docusaurus.config.ts
- package.json
- pnpm-lock.yaml
> feat(docs): Integrate google analytics

- .prettierignore
- .vscode/extensions.json
- docs/partials/_tab-human-readable.mdx
- docs/partials/_tab-portfolio-tracking.mdx
- package.json
- pnpm-lock.yaml
- src/css/custom.scss
- src/modules/Dashboard/BuyCredits.tsx
- src/modules/Dashboard/PaymentHistory.tsx
- src/modules/Dashboard/SignInButton.tsx
- src/pages/dashboard.tsx
Format on commit moving forward
> chore(docs): Format on commit

- docs/api/endpoints/onchain-identity.md
> fix(studio): Missing bracket in Account vars

- src/css/custom.scss
- src/modules/Dashboard/BuyCredits.tsx
Extract the `<input>` styling so it can be used in other places
> Extract input style

- docs/api/pricing.mdx
- src/components/SignInDashboard.tsx
> rework signin component to take text as a prop and added buy credits button to pricing page

- src/components/QuickLinks.tsx
> add quicklink (calculator)

- src/modules/Dashboard/BuyCredits.tsx
Adds the holiday special for credits : 25% off over 1M, 33% off over 10M.
> smol(studio): Holiday bulk purchase special

- src/modules/Dashboard/BuyCredits.tsx
> adjust price

- src/components/Media.tsx
- src/modules/Token/Token.tsx
Non-JS based toggle of media source
> refactor(web): Non-JS dark/light media

- docs/api/endpoints/portfolio.md
Adds the docs for the newly added compute mutations and queries.
> smol(studio): Add job status jobs docs

- src/components/RedirectToLogin.tsx
- src/helpers/useSignIn.ts
- src/modules/Dashboard/SignInButton.tsx
- src/pages/dashboard.tsx
- src/pages/login.tsx
Auto-prompt login when at /dashboard
> Auto-prompt login

- src/components/PricingCalculator.tsx
- src/helpers/formatters.ts
- src/modules/Dashboard/BuyCredits.tsx
Align amounts to format in US $
> format in US $

- docs/api/endpoints/portfolio.md
> smol(studio): Adjust docs for compute

- docs/api/pricing.mdx
- src/modules/Dashboard/BuyCredits.tsx
Removes discounts for credits that we had for holidays. 
BE needs to be merged before this goes in prod.
> smol(studio): Remove holiday pricing discounts
